### PR TITLE
Add supported image size

### PR DESCRIPTION
**Pull request by vmarci21**

### CODE REVIEW

**Comment by utkarshgpta** [comment]
Is it working correctly @vmarci21 ?

**Comment by vmarci21** [comment]
@UtkarshGpta  Yes, i tested it. I found terse image sizes. (Maybe there is more size, but I checked all sizes width Wikipedia screen resolution page.)

**Comment by utkarshgpta** [comment]
@vmarci That's cool! We need to see to it that it works on dual monitors too. Have you tried that?

**Comment by vmarci21** [comment]
@UtkarshGpta  I can't tested in dual monitor, but I thinking it working. (I don't change the finding screen size code)

**Comment by utkarshgpta** [comment]
@shoeyn Can you please check whether it works with dual monitors!

**Comment by shoeyn** [comment]
@UtkarshGpta yes, new mods still work great for me. Good job @vmarci21

**Pull request merged**
